import csv
import os
import django

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Exoplanets_ok.settings')
django.setup()

from Exoplanets_web.models import Exoplanet


def import_csv(filepath):
    with open(filepath, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Exoplanet.objects.create(
                pl_name=row['pl_name'] or None,
                hostname=row['hostname'] or None,
                default_flag=row['default_flag'] or None,
                sy_snum=row['sy_snum'] or None,
                sy_pnum=row['sy_pnum'] or None,
                discoverymethod=row['discoverymethod'] or None,
                disc_year=row['disc_year'] or None,
                disc_facility=row['disc_facility'] or None,
                soltype=row['soltype'] or None,
                pl_controv_flag=row['pl_controv_flag'] or None,
                pl_refname=row['pl_refname'] or None,
                pl_orbper=row['pl_orbper'] or None,
                pl_orbpererr1=row['pl_orbpererr1'] or None,
                pl_orbpererr2=row['pl_orbpererr2'] or None,
                pl_orbperlim=row['pl_orbperlim'] or None,
                pl_orbsmax=row['pl_orbsmax'] or None,
                pl_orbsmaxerr1=row['pl_orbsmaxerr1'] or None,
                pl_orbsmaxerr2=row['pl_orbsmaxerr2'] or None,
                pl_orbsmaxlim=row['pl_orbsmaxlim'] or None,
                pl_rade=row['pl_rade'] or None,
                pl_radeerr1=row['pl_radeerr1'] or None,
                pl_radeerr2=row['pl_radeerr2'] or None,
                pl_radelim=row['pl_radelim'] or None,
                pl_radj=row['pl_radj'] or None,
                pl_radjerr1=row['pl_radjerr1'] or None,
                pl_radjerr2=row['pl_radjerr2'] or None,
                pl_radjlim=row['pl_radjlim'] or None,
                pl_bmasse=row['pl_bmasse'] or None,
                pl_bmasseerr1=row['pl_bmasseerr1'] or None,
                pl_bmasseerr2=row['pl_bmasseerr2'] or None,
                pl_bmasselim=row['pl_bmasselim'] or None,
                pl_bmassj=row['pl_bmassj'] or None,
                pl_bmassjerr1=row['pl_bmassjerr1'] or None,
                pl_bmassjerr2=row['pl_bmassjerr2'] or None,
                pl_bmassjlim=row['pl_bmassjlim'] or None,
                pl_bmassprov=row['pl_bmassprov'] or None,
                pl_orbeccen=row['pl_orbeccen'] or None,
                pl_orbeccenerr1=row['pl_orbeccenerr1'] or None,
                pl_orbeccenerr2=row['pl_orbeccenerr2'] or None,
                pl_orbeccenlim=row['pl_orbeccenlim'] or None,
                pl_insol=row['pl_insol'] or None,
                pl_insolerr1=row['pl_insolerr1'] or None,
                pl_insolerr2=row['pl_insolerr2'] or None,
                pl_insollim=row['pl_insollim'] or None,
                pl_eqt=row['pl_eqt'] or None,
                pl_eqterr1=row['pl_eqterr1'] or None,
                pl_eqterr2=row['pl_eqterr2'] or None,
                pl_eqtlim=row['pl_eqtlim'] or None,
                ttv_flag=row['ttv_flag'] or None,
                st_refname=row['st_refname'] or None,
                st_spectype=row['st_spectype'] or None,
                st_teff=row['st_teff'] or None,
                st_tefferr1=row['st_tefferr1'] or None,
                st_tefferr2=row['st_tefferr2'] or None,
                st_tefflim=row['st_tefflim'] or None,
                st_rad=row['st_rad'] or None,
                st_raderr1=row['st_raderr1'] or None,
                st_raderr2=row['st_raderr2'] or None,
                st_radlim=row['st_radlim'] or None,
                st_mass=row['st_mass'] or None,
                st_masserr1=row['st_masserr1'] or None,
                st_masserr2=row['st_masserr2'] or None,
                st_masslim=row['st_masslim'] or None,
                st_met=row['st_met'] or None,
                st_meterr1=row['st_meterr1'] or None,
                st_meterr2=row['st_meterr2'] or None,
                st_metlim=row['st_metlim'] or None,
                st_metratio=row['st_metratio'] or None,
                st_logg=row['st_logg'] or None,
                st_loggerr1=row['st_loggerr1'] or None,
                st_loggerr2=row['st_loggerr2'] or None,
                st_logglim=row['st_logglim'] or None,
                sy_refname=row['sy_refname'] or None,
                rastr=row['rastr'] or None,
                ra=row['ra'] or None,
                decstr=row['decstr'] or None,
                dec=row['dec'] or None,
                sy_dist=row['sy_dist'] or None,
                sy_disterr1=row['sy_disterr1'] or None,
                sy_disterr2=row['sy_disterr2'] or None,
                sy_vmag=row['sy_vmag'] or None,
                sy_vmagerr1=row['sy_vmagerr1'] or None,
                sy_vmagerr2=row['sy_vmagerr2'] or None,
                sy_kmag=row['sy_kmag'] or None,
                sy_kmagerr1=row['sy_kmagerr1'] or None,
                sy_kmagerr2=row['sy_kmagerr2'] or None,
                sy_gaiamag=row['sy_gaiamag'] or None,
                sy_gaiamagerr1=row['sy_gaiamagerr1'] or None,
                sy_gaiamagerr2=row['sy_gaiamagerr2'] or None,
                rowupdate=row['rowupdate'] or None,
                pl_pubdate=row['pl_pubdate'] or None,
                releasedate=row['releasedate'] or None,
            )

if __name__ == '__main__':
    import_csv('') # your path to EXOPLANETAS.csv
